version: 2.1

jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:13.12-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-{{ arch }}-{{ .Branch }}-
            - yarn-packages-
      - run:
          name: Install dependencies
          command: yarn --immutable --cache-folder .cache/yarn
      - save_cache:
          paths:
            - .cache/yarn
          key: yarn-packages-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Setup GCP
          command: |
            echo $CLIENT_SECRET | base64 -d > client-secret.json
            export GOOGLE_APPLICATION_CREDENTIALS="client-secret.json"
      - run:
          name: Take screenshot
          command: yarn run screenshot
      - run:
          name: Run regression test
          command: yarn run regression
